version: '3'
services:
  react-nginx-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: react-nginx-app
    container_name: react-nginx-container
    ports:
      - "3000:80"
    #expose:
      #- "3000"  
    #volumes:
      #- ./src:/usr/src/myapp/src
      #- ./public:/usr/src/myapp/public
    #environment:
      #- NODE_ENV=environment
    #command: npm start